services:
  - type: web
    name: flodrama-scraper
    runtime: python
    repo: https://github.com/flori92/flodrama-scraper-relay
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0